name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop


defaults:
  run:
    working-directory: libs/hakawati

jobs:
  package-version-check: 
    name: version check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      # ----------------------------------------------------
      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org/'
      # ----------------------------------------------------
      - name: Compare npm with local (versions)
        uses: Rober19/compare-npm-versions-ci@master
        id: package_version
        with:
          path: './libs/hakawati'
          npm_package_name: hakawati
      # ----------------------------------------------------
      - name: Get version
        run: |
          echo "Version is  ${{ steps.package_version.outputs.version }} "    
          echo "Version NPM is  ${{ steps.package_version.outputs.pkg_npm_version }} "
      # ----------------------------------------------------
      - name: Version Issue
        if: steps.package_version.outputs.npm_is_greater == 'true'
        run: |
          echo "Package will not be deployed due to version number must increase"


  # lint:
  #   name: Lint check
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: '14.x'
  #     - run: yarn install
  #     - run: yarn lint

  # build-check:
  #   name: Build check
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: '14.x'
  #     - run: yarn install
  #     - run: yarn build-lib

  # build-publish:
  #   name: Publish build to NPM registry
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 14
  #         registry-url: https://registry.npmjs.org/
  #     - run: |
  #         if [[ $GITHUB_EVENT_NAME != "pull_request" ]]; then
  #           yarn install
  #           yarn build-lib
  #           yarn publish --access=public
  #         else
  #           echo "+++++ No Publish on PR event +++++++++"
  #         fi
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
