name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint:
    name: Build check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn install
      - run: yarn lint

  build-check:
    name: Lint check
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn install
      - run: yarn build-lib

  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: |
          if [[ $GITHUB_EVENT_NAME != "pull_request" ]]; then
            yarn install
            yarn build-lib
            yarn publish --access=public
          else
            echo "+++++ No Publish on PR event +++++++++"
          fi
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
